# Generated by Django 6.1.1 on 2026-09-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_jugador', models.CharField(max_length=50)),
                ('puntaje', models.IntegerField()),
                ('tiempo_jugado_minutos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('partida_completada', models.BooleanField(default=True)),
                ('fecha_partida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'puntuaciones',
                'ordering': ['-puntaje', 'tiempo_jugado_minutos'],
            },
        ),
    ]
